HW02
AndreiRubinJ/otusgo pull request #1
Opened 2024-08-18 09:51 UTC by AndreiRubinJ

2024-08-18 15:35 UTC, vladislavmass requested changes

2024-08-18 15:35 UTC, vladislavmass commented on hw02_fix_app/main.go
>  func init() {
Функции init не должно быть. Надо было просто переименовать всю функцию init в main

2024-08-18 15:35 UTC, vladislavmass commented on hw02_fix_app/main.go
> +	fmt.Print("Done ...")
Этого быть не должно

2024-08-18 15:35 UTC, vladislavmass commented on hw02_fix_app/reader/reader.go
> +		fmt.Printf("Error: %v", err)
Ошибку надо возвращать. Нет никакого смысла парсить файл, который не считали. `return nil,err`

2024-08-18 15:35 UTC, vladislavmass commented on hw02_fix_app/reader/reader.go
> +		return nil, nil
Ошибку надо возвращать. `return nil,err`

2024-08-18 15:35 UTC, vladislavmass commented on hw02_fix_app/reader/reader.go
> +	res := data
Эта строчка не имеет смысла.

2024-08-18 16:19 UTC, AndreiRubinJ commented on hw02_fix_app/main.go
>  func init() {
поправил

2024-08-18 16:19 UTC, AndreiRubinJ commented on hw02_fix_app/main.go
> +	fmt.Print("Done ...")
удалил

2024-08-18 16:19 UTC, AndreiRubinJ commented on hw02_fix_app/reader/reader.go
> +		fmt.Printf("Error: %v", err)
поправил

2024-08-18 16:19 UTC, AndreiRubinJ commented on hw02_fix_app/reader/reader.go
> +		return nil, nil
поправил

2024-08-18 16:20 UTC, AndreiRubinJ commented on hw02_fix_app/reader/reader.go
> +	res := data
удалил

2024-08-19 04:52 UTC, vladislavmass approved these changes

2024-08-19 04:52 UTC, vladislavmass commented on hw02_fix_app/go.mod
> +module hw02_fix_app
Все еще неверное имя модуля. Верное имя модуля в данном случае это `github.com/AndreiRubinJ/otusgo/hw02_fix_app`

2024-08-19 04:53 UTC, vladislavmass requested changes
Необходимо поправить имя модуля

2024-08-19 06:34 UTC, AndreiRubinJ commented on hw02_fix_app/go.mod
> +module hw02_fix_app
сомнительно ну OK

2024-08-19 06:38 UTC, vladislavmass commented on hw02_fix_app/go.mod
> +module hw02_fix_app
именно с таким именем будет работать утилита go get.  `https://go.dev/ref/mod#module-path`

2024-08-19 06:39 UTC, vladislavmass approved these changes

2024-08-23 14:44 UTC, merged